site_name: Minimalist Interior Ballistics

site_author: Jinpeng Zhai

nav:
  - Home: index.md
  - Theory: 
    - Index: theory.md
    - Propellant: propellant.md
    - Interior Ballistics: interior_ballistics.md

# theme: 
#   name: null
#   custom_dir: 'cinder'
theme:
  name: terminal
  features:
    - navigation.side.indexes

markdown_extensions:
  - toc
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js